#' Problems panel grob
#'
#' `problemsGrob()` creates a grid grob laying out arithmetic problems
#' (as generated by [generate_math_problems()]) in long-form "stacked"
#' style: right-aligned operands stacked atop each other, the operation
#' symbol beside the bottom operand, a rule line underneath, and blank
#' space below the rule for the answer (plus space above the operands
#' for carry/borrow marks).  Problems are laid out in reading order in a
#' column/row grid filling a `[0, 1] x [0, 1]` viewport.
#'
#' @param problems A data frame as returned by [generate_math_problems()]
#'                 (i.e. with columns `problem`, `op`, and `operands`).
#' @param ncol Number of columns of problems.  The default (`NULL`) picks
#'             3 columns for up to 18 problems and 4 columns otherwise.
#' @param nrow Number of rows of problems.  The default (`NULL`) picks
#'             enough rows to fit the problems but at least 6 (so a puzzle
#'             with few problems keeps the same row height instead of
#'             stretching each problem to fill the panel).
#' @param gp A [grid::gpar()] object.
#' @param name A character identifier (for the grob).
#' @param vp A [grid::viewport()] object (or `NULL`).
#' @return A [grid::gTree()] object.
#' @importFrom grid gList gpar gTree segmentsGrob textGrob
#' @examples
#' if (require("grid", quietly = TRUE)) {
#'     set.seed(42)
#'     problems <- generate_math_problems(c(34, 37, 67, 64, 34))
#'     grid.newpage()
#'     vp <- viewport(width = unit(5, "in"), height = unit(7.5, "in"))
#'     grid.draw(problemsGrob(problems, vp = vp))
#' }
#' @export
problemsGrob <- function(
	problems,
	ncol = NULL,
	nrow = NULL,
	gp = gpar(col = "black", lwd = 2),
	name = NULL,
	vp = NULL
) {
	stopifnot(
		"`problems` must be a data frame with columns `problem`, `op`, and `operands`" = is.data.frame(
			problems
		) &&
			all(c("problem", "op", "operands") %in% names(problems)),
		"`problems` must have at least one problem" = nrow(problems) >= 1L,
		"each problem must have at least two operands" = all(lengths(problems$operands) >= 2L)
	)
	n <- nrow(problems)
	if (is.null(ncol)) {
		ncol <- if (n <= 18L) 3L else 4L
	}
	if (is.null(nrow)) {
		nrow <- max(ceiling(n / ncol), 6L)
	}
	stopifnot("`ncol` times `nrow` must fit all the problems" = ncol * nrow >= n)

	# cell (column, row) of each problem, in reading order
	cw <- 1 / ncol
	ch <- 1 / nrow
	i <- seq_len(n)
	x_left <- ((i - 1L) %% ncol) * cw
	y_top <- 1 - ((i - 1L) %/% ncol) * ch

	# within each cell (fractions of the cell) the rule line sits at
	# 0.62 down from the top, operands stack above it one line apart,
	# and everything below the rule is left blank for the answer
	lh <- 0.2 * ch
	y_rule <- y_top - 0.62 * ch
	k <- lengths(problems$operands)
	j <- sequence(k)
	y_operand <- rep(y_rule, k) + (rep(k, k) - j + 0.6) * lh

	operands <- textGrob(
		unlist(problems$operands),
		x = rep(x_left, k) + 0.78 * cw,
		y = y_operand,
		just = "right",
		name = "operands"
	)
	symbols <- textGrob(
		c(add = "+", subtract = "\u2212", multiply = "\u00d7")[problems$op],
		x = x_left + 0.22 * cw,
		y = y_rule + 0.6 * lh,
		just = "left",
		name = "op_symbols"
	)
	rules <- segmentsGrob(
		x0 = x_left + 0.18 * cw,
		y0 = y_rule,
		x1 = x_left + 0.86 * cw,
		y1 = y_rule,
		name = "rules"
	)
	labels <- textGrob(
		paste0(problems$problem, "."),
		x = x_left + 0.04 * cw,
		y = y_rule + (k - 0.4) * lh,
		just = "left",
		gp = gpar(cex = 0.8),
		name = "problem_labels"
	)

	gTree(
		children = gList(rules, operands, symbols, labels),
		gp = gp,
		name = name,
		vp = vp,
		cl = "problems_grob"
	)
}
